version: "3.9"
services:
    bot:
        build: .
        links:
            - postgres
        env_file:
            - .env
        init: true
        stop_signal: SIGINT
    postgres:
        image: postgres:13.1-alpine
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres_data:

