"""add delete columns

Revision ID: 04e8d0233243
Revises: 
Create Date: 2021-02-09 00:16:16.360758

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "04e8d0233243"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("delete_cancelled", sa.Boolean(), nullable=True)
    )
    op.add_column("messages", sa.Column("delete_failed", sa.Boolean(), nullable=True))
    op.execute("UPDATE messages SET delete_cancelled = false")
    op.execute("UPDATE messages SET delete_failed = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "delete_failed")
    op.drop_column("messages", "delete_cancelled")
    # ### end Alembic commands ###
