"""attempt counter

Revision ID: c92fec5367d1
Revises: 04e8d0233243
Create Date: 2021-02-11 18:04:21.019319

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c92fec5367d1"
down_revision = "04e8d0233243"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("delete_attempt", sa.Integer(), nullable=True))
    op.execute("UPDATE messages SET delete_attempt = 0")
    op.execute("UPDATE messages SET delete_attempt = 1 WHERE deleted = true")
    op.alter_column("messages", "delete_attempt", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "delete_attempt")
    # ### end Alembic commands ###
